Topology manger
LicAiBeerLab/auto-robotics-design pull request #25
Opened 2024-07-07 12:22 UTC by MikhailChaikovskii

1. Добавлен новый способ генерировать графы - graph_manager_2l
2. Добавлен вариант мультикритериальной проблемы работающей с новый генератором
3. добавлены ноутбуки с примерами использования

2024-07-08 17:27 UTC, Huowl requested changes

2024-07-08 21:58 UTC, MikhailChaikovskii commented on auto_robot_design/generator/topologies/graph_manager_2l.py
> +    def build_4l_asymmetric(self, connection_list: float):
Не особо по-умному, но для наших топологий работает. Я пока не придумал хороший вариант, для этого надо реально какой-то анализ графа делать

2024-07-08 22:02 UTC, MikhailChaikovskii commented on auto_robot_design/generator/topologies/graph_manager_2l.py
> +    if idx == 3:
не вижу одинаковых, в 3 ветка асимметричная

2024-07-09 10:23 UTC, Huowl approved these changes

2024-07-09 10:23 UTC, merged