Inverse kinematic update
LicAiBeerLab/auto-robotics-design pull request #28
Opened 2024-07-31 21:47 UTC by MikhailChaikovskii

1) Пачка всяких мелких изменений, типа добавки имён для ревордов, добавка данных в выходы с аггрегатора

2) Добавлены альтернативные способы считать ИК. Там ещё дорабатывать, но если их не слить, то потом количество изменений станет слишком большим

3) добавлены ноутбуки с попытками в аналитику, на которых я собственно и обнаружил всякие проблемы с разрывами в собираемости

2024-08-01 11:55 UTC, Huowl requested changes

2024-08-01 11:55 UTC, Huowl commented on auto_robot_design/pinokla/default_traj.py
> +def enhance_trajectory(trajectory: Tuple[np.array], initial_point=np.array([0, -0.4]), number_points=50):
поменять название

2024-08-01 11:55 UTC, Huowl commented on auto_robot_design/pinokla/closed_loop_kinematics.py
> +        q = pin.integrate(model, q, 0.5 * dq)
Почему 0.5

2024-08-01 21:35 UTC, MikhailChaikovskii commented on auto_robot_design/optimization/rewards/reward_base.py
> +            with open('cont_check.txt', 'a') as f:
А можно я сделаю чтобы каждый раз тебе email приходил когда не собирается механизм?

2024-08-01 21:37 UTC, MikhailChaikovskii commented on auto_robot_design/pinokla/closed_loop_kinematics.py
> +        q = pin.integrate(model, q, 0.5 * dq)
раньше этот вопрос никого не волновал, почему бы и нет, у тебя в открытой кинематики шаг 0.1 и никто не задавал вопросов, ну добавлю я ещё один параметр с дефолтным значением, который никто никогда не будет использовать

2024-08-02 10:39 UTC, Huowl approved these changes

2024-08-02 10:39 UTC, merged